name: synth-speech-eval
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
  - conda-forge
dependencies:
  - ffmpeg[version='>=6.0,<7.0']
  - cuda-toolkit
