output_dir : ./outputs/
path : ./inputs/
dataset_name : test
device : cpu
language: en

score_threshold : 4.9

saliency :
  saliency_interp_method : bilinear
  output_saliency_overlay : True

pdsm:
  k_method : percent
  k : 0.1
  preprocess : abs
  pool : l2_norm
