output_dir : ./outputs/
path : ./inputs/
dataset_name : test
language: en

score_threshold : 3

sq_ast_dims : ["mos", "noi", "dis", "col", "loud"]

saliency :
  saliency_method : "Flow"
  saliency_interp_method : nearest

pdsm :
  k_method : percent
  k : 0.1
  preprocess : abs
  pool : l2_norm

sq_ast :
  batch_size : 16

whisperx :
  batch_size : 32

kde : 
  bw_method : 0.10

plots : 
  output_pdsm_saliency_overlay : True
  output_joint_kde : True
  output_time_kde : True

  output_asr_confidence : True
  output_sys_violin : True
  output_sys_bar : True
  output_sys_pair : True
  output_sys_wav_chan : True
  output_freq_kde : True
  
  output_phoneme_hist : True
  output_double_phoneme_hist : True
  
  output_asr_confidence_violin : True